#pragma once

#include <ntifs.h>

#define KRNL_GET_BASEADDR CTL_CODE( FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS  )
#define KRNL_READ_MEM CTL_CODE( FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS  )
#define KRNL_WRITE_MEM CTL_CODE( FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS  )

NTSTATUS IrpCreateClose(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS IrpControl(PDEVICE_OBJECT DeviceObject, PIRP Irp);